version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the index.js code      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.js
    - app.json
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
